import type { Metadata } from "next";
import { Jua, Joti_One } from "next/font/google";
import "./globals.css";

const jua = Jua({
  variable: "--font-jua",
  subsets: ["latin"],
  weight: "400",
});
const joti_one = Joti_One({
  variable: "--font-joti",
  subsets: ["latin"],
  weight: "400",
});
export const metadata: Metadata = {
  title: "Hula",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${jua.variable} ${joti_one.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
